import { Gender } from './Gender';
import { Weapons } from './Weapons';
import { Group } from './Group';

export default [
  {
    uid: '1',
    memberAvatar: 'https://picsum.photos/200',
    isActive: true,
    isAdmin: true,
    firstName: 'Julien',
    lastName: 'Reig',
    birth: new Date(2000, 3, 6),
    phone: '01 23 45 67 89',
    emergencyPhone: '01 23 45 67 89',
    mail: 'mail@mail.com',
    medicalCertificat: 'ici',
    cerfa: '',
    paid: true,
    gender: Gender.MALE,
    weapons: [Weapons.FOIL, Weapons.EPEE],
    group: Group.M20,
    isChild: false
  },
  {
    uid: '2',
    memberAvatar: 'https://picsum.photos/200',
    isActive: false,
    isAdmin: false,
    firstName: 'Thomas',
    lastName: 'Durand',
    birth: new Date(1999, 3, 6),
    phone: '01 23 45 67 89',
    emergencyPhone: '01 23 45 67 89',
    mail: 'mail@mail.com',
    medicalCertificat: '',
    cerfa: 'là',
    paid: true,
    gender: Gender.MALE,
    weapons: [Weapons.EPEE],
    group: Group.SENIORS,
    isChild: false
  },
  {
    uid: '4',
    memberAvatar: 'https://picsum.photos/200',
    isActive: true,
    isAdmin: false,
    firstName: 'Sandrine',
    lastName: 'Tale',
    birth: new Date(1990, 7, 5),
    phone: '01 23 45 67 89',
    emergencyPhone: '01 23 45 67 89',
    mail: 'mail@mail.com',
    medicalCertificat: 'ici',
    cerfa: 'là',
    paid: true,
    gender: Gender.FEMALE,
    weapons: [Weapons.EPEE],
    group: Group.SENIORS,
    isChild: false
  },
  {
    uid: '5',
    memberAvatar: 'https://picsum.photos/200',
    isActive: true,
    isAdmin: false,
    firstName: 'Julie',
    lastName: 'Wat',
    birth: new Date(1951, 7, 5),
    phone: '01 23 45 67 89',
    emergencyPhone: '01 23 45 67 89',
    mail: 'mail@mail.com',
    medicalCertificat: 'ici',
    cerfa: 'là',
    paid: true,
    gender: Gender.FEMALE,
    weapons: [Weapons.SABRE],
    group: Group.VETERANS3,
    isChild: false
  },
  {
    uid: '6',
    memberAvatar: 'https://picsum.photos/200',
    isActive: true,
    isAdmin: false,
    firstName: 'Jean',
    lastName: 'Tale',
    birth: new Date(1970, 3, 6),
    phone: '01 23 45 67 89',
    emergencyPhone: '01 23 45 67 89',
    mail: 'mail@mail.com',
    medicalCertificat: 'ici',
    cerfa: 'là',
    paid: true,
    gender: Gender.MALE,
    weapons: [Weapons.EPEE],
    group: Group.VETERANS2,
    isChild: false
  },
  {
    uid: '6',
    memberAvatar: 'https://picsum.photos/200',
    isActive: true,
    isAdmin: false,
    firstName: 'Jean',
    lastName: 'Petit',
    birth: new Date(2008, 3, 6),
    phone: '01 23 45 67 89',
    emergencyPhone: '01 23 45 67 89',
    mail: 'mail@mail.com',
    medicalCertificat: 'ici',
    cerfa: 'là',
    paid: true,
    gender: Gender.MALE,
    weapons: [Weapons.FOIL],
    group: Group.M11,
    isChild: true
  },
  {
    uid: '7',
    memberAvatar: 'https://picsum.photos/200',
    isActive: true,
    isAdmin: false,
    firstName: 'Marie',
    lastName: 'Poppins',
    birth: new Date(2012, 3, 6),
    phone: '01 23 45 67 89',
    emergencyPhone: '01 23 45 67 89',
    mail: 'mail@mail.com',
    medicalCertificat: 'ici',
    cerfa: 'là',
    paid: false,
    gender: Gender.FEMALE,
    weapons: [Weapons.FOIL],
    group: Group.M7,
    isChild: true
  }
];
